### ISSUE TITLE
Release a new major - v7.0.0

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#661]
Todo:

- [x] set the default entry point to `sweetalert2.all`[~~`.min`~~](https://github.com/limonte/sweetalert2/issues/661#issuecomment-341055934)`.js` (https://github.com/limonte/sweetalert2/issues/612#issuecomment-333306384)  - done in https://github.com/limonte/sweetalert2/pull/692
- [x] `useRejections` should be `false` by default (https://github.com/limonte/sweetalert2/issues/485) - done in https://github.com/limonte/sweetalert2/pull/693
- [x] `display: flex` for `buttons-wrapper` (https://github.com/limonte/sweetalert2/issues/653) - done in https://github.com/limonte/sweetalert2/pull/672

**Comment by mattbrunetti** [comment]
@limonte What time frame are you looking at for this release? 

It would be nice to have the `expectRejections` option also in the current major (v6) before changing the defaults for both to `false`, though not totally necessary.

**Comment by mattbrunetti** [comment]
I think it would be easier for users to adapt to both of these changes to default behavior in one step rather than 2, since they are very similar.

**Comment by toverux** [comment]
@mattbrunetti That could be implemented right into version 7, right? I guess we're not that hurry ;) (oh and uh, can you just edit your comment to a link about the discussion? Can't find anything about expectRejections here https://github.com/limonte/sweetalert2/search?q=expectRejections&type=Issues&utf8=%E2%9C%93)

**Comment by mattbrunetti** [comment]
@toverux You're right, I guess there is no need to implement it in v6 at all. 

Great, if this release can wait a few days, I will plan to close off #485 this weekend :)

@toverux See my edited comment and let me know if it makes sense

**Comment by limonte** [comment]
> Great, if this release can wait a few days, I will plan to close off #485 this weekend :)

Absolutely! Many thanks, @mattbrunetti!

**Comment by acupajoe** [comment]
@limonte note that `.buttons-wrapper` will transition to flex at the completion of #670

**Comment by limonte** [comment]
@samturrell @toverux @acupajoe 

> set the default entry point to sweetalert2.all.min.js

in the next major, should we set the default entry point to sweetalert2.all.js instead of sweetalert2.all.**min.**js? It would be easier for developers to debug and report issues.

**Comment by toverux** [comment]
Agreed. The `main` entry is, by convention, expected to lead to a non-minified file. You then minify yourself in the build process, in production mode.
.min.css and .min.js files are more likely to be used via CDNs and by users that don't use the npm package.

**Comment by samturrell** [comment]
Agree with @toverux.

**Comment by limonte** [comment]
in https://github.com/limonte/sweetalert2/pull/693 we're discussing dropping `useRejections` in the new major, any objections?

**Comment by limonte** [comment]
Quick update: almost there, the only one remained PR I would like to be included in `v7.0.0` is https://github.com/limonte/sweetalert2/pull/674

@mattbrunetti what do you think, will you have time to polish it accordingly to the @toverux's latest comment?

**Comment by zenflow** [comment]
@mattbrunetti Absolutely, I'll do so at lunch today

**Comment by limonte** [comment]
oops, accidentally closed the issue :)

Many thanks @mattbrunetti!

**Comment by limonte** [comment]
:tada: :tada: :tada: 

https://github.com/limonte/sweetalert2/releases/tag/v7.0.0

:tada: :tada: :tada: 

All collaborators should have the edit permission for release notes, feel free to add/change if I forgot something to mention.

@zenflow you are the collaborator now, welcome! It's my pleasure to have you in this small but extremely efficient open-source team :sunglasses: Do you have a public email address so I can include it in the [collaborators section of package.json](https://github.com/limonte/sweetalert2/blob/master/package.json#L50)?

**Comment by toverux** [comment]
Yeah! Thanks to the people who have contributed on v.7!

**Comment by zenflow** [comment]
@limonte @toverux @birjolaxew @samturrell @acupajoe @patrickhlauke Thank you for accepting me on this very excellent team! It is really an honor. I very much look forward to working more with all of you! 😄 

@limonte Awesome! You can use this email address - zenflow87@gmail.com 👍

**Comment by toverux** [comment]
Annnd I'm also happy to annouce that v7 allowed [ngx-sweetalert2](https://github.com/toverux/ngx-sweetalert2)'s v3 to do its coming out: https://github.com/toverux/ngx-sweetalert2/releases/tag/v3.0.0

It's quite of a big release too -- if you were wondering why I'm comitting so little on Swal2, that's because I prefer to give some help here (in issues, reviews, advices, etc) and focus my developement efforts on the Angular integration.

That v3 has an interesting feature, too: using dynamic, Angular-managed DOM in SweetAlerts:

```html
<swal title="Fill the form, rapidly">
  <!-- This form will be displayed as the alert main content
       Targets the alert's main content zone by default -->
  <form *swalPartial [formControl]="myForm">
    ...
  </form>
        
  <!-- This targets the confirm button's inner content
       Notice the usage of ng-container to avoid creating an useless DOM element inside the button -->
  <ng-container *swalPartial="swalTargets.confirmButton">
    Send ({{ secondsLeft }} seconds left)
  </ng-container>
<swal>
```

Again, thanks again to all the contributors! This is a small library with a very limited scope, and yet, it helps many people (100K DL/mo), and federated a group of passionate contributors, thanks to our [benevolent dictator for life](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) @limonte :smile:

**Comment by limonte** [comment]
Congrats @toverux! The release notes for v3 looks professional :+1: 

> And, thanks again to all the contributors! This is a small library with a very limited scope, and yet, it helps many people (100K DL/mo), and federated a group of passionate contributors, thanks to our benevolent dictator for life @limonte

:laughing:
